FROM python:3.11.0-slim

WORKDIR /app
ENV UV_LINK_MODE=copy

COPY ./requirements.txt /app/requirements.txt

RUN --mount=type=cache,target=/var/lib/buildkit/.cache pip install --cache-dir=/var/lib/buildkit/.cache uv

RUN --mount=type=cache,target=/var/lib/buildkit/.cache uv pip install --cache-dir=/var/lib/buildkit/.cache -r requirements.txt --system

COPY . /app/

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]