FROM python:3.10.0-slim

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN --mount=type=cache,target=/root/.cache/pip-test pip install --cache-dir=/root/.cache/pip-test -r requirements.txt

RUN --mount=type=cache,target=/root/.cache/pip-test ls -ltr /root/.cache/pip-test

COPY . /app/

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]