FROM python:3.11.0-slim

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN --mount=type=cache,target=/var/lib/buildkit/.cache pip install -r requirements.txt

COPY . /app/

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]