FROM python:3.11.0-slim

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install uv

RUN uv pip install -r requirements.txt --system

COPY . /app/

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]