FROM tfy.jfrog.io/tfy-mirror/library/python:3.10.2-slim

WORKDIR /app

RUN echo "Starting the build again"

COPY ./requirements.txt /app/requirements.txt

RUN --mount=type=cache,target=/root/.cache/pip1 pip install --cache-dir=/root/.cache/pip1 -r requirements.txt

RUN --mount=type=cache,target=/root/.cache/pip1 ls -ltr /root/.cache/pip1

COPY . /app/

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]