name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: false
          swap-storage: false
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Cache Docker layers for Dockerfile uv
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-dockerfile2  
          key: ${{ runner.os }}-buildx-dockerfile2-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-dockerfile2-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_INTERNAL_REPOSITORY }}
          username: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_INTERNAL_USERNAME }}
          password: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_INTERNAL_PASSWORD }}

      - name: Build and push Docker image with uv
        uses: docker/build-push-action@v5
        with:
          context: .  
          file: ./Dockerfile.uv  
          push: true
          tags: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_INTERNAL_REPOSITORY }}/build-with-uv:latest
          cache-from: type=local,src=/tmp/.buildx-cache-dockerfile2
          cache-to: type=local,dest=/tmp/.buildx-cache-dockerfile2