name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Trigger the action when pushing to the main branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Cache for the first Dockerfile
      - name: Cache Docker layers for Dockerfile pip
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-dockerfile1  # Cache directory for Dockerfile 1
          key: ${{ runner.os }}-buildx-dockerfile1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-dockerfile1-

      # Cache for the second Dockerfile
      - name: Cache Docker layers for Dockerfile uv
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-dockerfile2  # Cache directory for Dockerfile 2
          key: ${{ runner.os }}-buildx-dockerfile2-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-dockerfile2-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_REGISTRY_URL }}
          username: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_PRIVATE_USERNAME }}
          password: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_PRIVATE_PASSWORD }}

      - name: Build and push Docker image with pip
        uses: docker/build-push-action@v5
        with:
          context: .  # Context for the first Dockerfile
          file: ./Dockerfile.pip  # Path to the first Dockerfile
          push: true
          tags: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_REGISTRY_URL }}/build-with-pip:latest
          cache-from: type=local,src=/tmp/.buildx-cache-dockerfile1
          cache-to: type=local,dest=/tmp/.buildx-cache-dockerfile1

      - name: Build and push Docker image with uv
        uses: docker/build-push-action@v5
        with:
          context: .  # Context for the second Dockerfile
          file: ./Dockerfile.uv  # Path to the second Dockerfile
          push: true
          tags: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_REGISTRY_URL }}/build-with-uv:latest
          cache-from: type=local,src=/tmp/.buildx-cache-dockerfile2
          cache-to: type=local,dest=/tmp/.buildx-cache-dockerfile2
