name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Cache for the first Dockerfile
      - name: Cache Docker layers for Dockerfile pip
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-dockerfile1  # Cache directory for Dockerfile 1
          key: ${{ runner.os }}-buildx-dockerfile1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-dockerfile1-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.TRUEFOUNDRY_ARTIFACTORY_INTERNAL_REPOSITORY }}
          username: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_INTERNAL_USERNAME }}
          password: ${{ secrets.TRUEFOUNDRY_ARTIFACTORY_INTERNAL_PASSWORD }}

      - name: Build Docker image with pip
        run: |
          start_time=$(date +%s)
          docker buildx build --file ./Dockerfile.pip --tag latest --cache-from=type=local,src=/tmp/.buildx-cache-dockerfile1 --cache-to=type=local,dest=/tmp/.buildx-cache-dockerfile1 --load .  
          end_time=$(date +%s)
          build_duration=$((end_time - start_time))
          echo "Image with pip build time: $build_duration seconds"
      
      - name: Measure push time for Docker image with pip
        run: |
          start_time=$(date +%s)
          docker tag latest ${{ vars.TRUEFOUNDRY_ARTIFACTORY_INTERNAL_REPOSITORY }}/build-with-pip:latest
          docker push ${{ vars.TRUEFOUNDRY_ARTIFACTORY_INTERNAL_REPOSITORY }}/build-with-pip:latest
          end_time=$(date +%s)
          push_duration=$((end_time - start_time))
          echo "Image eith pip push time: $push_duration seconds"
